name: changeset test

on:
    push:
        branches:
            - master

jobs:
    up:
        name: Update
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set Node.js 12.x
              uses: actions/setup-node@master
              with:
                  node-version: 12.x

            - name: yarn install
              run: yarn install
            
            - name: Create Release Pull Request
              uses: changesets/action@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}